services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8000:8080" # Открыт только этот сервис
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network
    depends_on:
      - frontend-manager
      - model
      - pdf

  frontend-manager:
    build:
      context: ./frontendmanager
      dockerfile: Dockerfile
    container_name: frontend-manager
    expose:
      - "8080" # Доступ только внутри сети
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: model
    expose:
      - "8080" # Доступ только внутри сети
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  pdf:
    build:
      context: ./pdf
      dockerfile: Dockerfile
    container_name: pdf
    expose:
      - "8080" # Доступ только внутри сети
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
