services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "${GATEWAY_EXTERNAL_PORT}:${GATEWAY_INTERNAL_PORT}"
    networks:
      - app-network
    depends_on:
      - frontend-manager
      - model
      - pdf
    env_file:
      - .env

  frontend-manager:
    build:
      context: ./frontendmanager
      dockerfile: Dockerfile
    container_name: frontend-manager
    expose:
      - "${FRONTEND_MANAGER_INTERNAL_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: model
    expose:
      - "${MODEL_INTERNAL_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  pdf:
    build:
      context: ./pdf
      dockerfile: Dockerfile
    container_name: pdf
    expose:
      - "${PDF_INTERNAL_PORT}"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
