services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "${GATEWAY_EXTERNAL_PORT}:${GATEWAY_INTERNAL_PORT}"
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          target: ./gateway/target/Gateway-0.0.1.jar
          path: ./gateway/target

    depends_on:
      - model
      - pdf
    env_file:
      - .env

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: model
    expose:
      - "${MODEL_INTERNAL_PORT}"
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          target: ./model/target/Model-0.0.1.jar
          path: ./model/target
    env_file:
      - .env

  pdf:
    build:
      context: ./pdf
      dockerfile: Dockerfile
    container_name: pdf
    expose:
      - "${PDF_INTERNAL_PORT}"
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          target: ./pdf/target/Pdf-0.0.1.jar
          path: ./pdf/target
    env_file:
      - .env